### ISSUE TITLE
Misleading error message on ENOENT

### ISSUE THREAD

**Issue by katexochen** [kmxz/overlayfs-tools#22]
When a given directory does not exist, the tool currently says it was not specified
```
strace overlay diff --lowerdir=/sysroot
...
readlink("/sysroot", 0x7ffdfc3f36c0, 1023) = -1 ENOENT (No such file or directory)
write(2, "Lower directory not specified.\n", 31Lower directory not specified.
) = 31
```

Would be nice to print that the directory does not exist instead.

Also, adding a `--version` flag and tagging releases would be a good idea. This tool is packaged for fedora, but it is impossible to say at what code state.

**Comment by UVV-gh** [comment]
Version is a good idea. Although I'd prefer to have a proper build system for that (I'm inclined to meson right now).

For the issue with the misleading message, could you please create a PR?

**Comment by katexochen** [comment]
I'll see if I can find the time for a PR. You could also add `good-first-issue` label.
