### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by herry13** [kmxz/overlayfs-tools#5]
Hi @kmxz. Would it be possible to add a license file into this repo? I plan to create an APK package for your software. Thanks.

**Comment by kmxz** [comment]
I got no idea what kind of license to use.
GPL-family license is a bit too strong.

Maybe I'll put [WTFPL](http://www.wtfpl.net/txt/copying/). Is that okay?

**Comment by herry13** [comment]
Sure, that's OK.

**Comment by kmxz** [comment]
Added.
