### ISSUE TITLE
Compile on debian buster fails

### ISSUE THREAD

**Issue by mstormi** [kmxz/overlayfs-tools#8]
[22:24:56] root@devpi:/tmp/zr/overlayfs-tools# make
gcc -Wall -std=c99 -c main.c
In file included from main.c:16:
/usr/include/linux/stat.h:56:8: error: redefinition of ‘struct statx_timestamp’
 struct statx_timestamp {
        ^~~~~~~~~~~~~~~
In file included from /usr/include/arm-linux-gnueabihf/sys/stat.h:446,
                 from main.c:14:
/usr/include/arm-linux-gnueabihf/bits/statx.h:25:8: note: originally defined here
 struct statx_timestamp
        ^~~~~~~~~~~~~~~
In file included from main.c:16:
/usr/include/linux/stat.h:99:8: error: redefinition of ‘struct statx’
 struct statx {
        ^~~~~
In file included from /usr/include/arm-linux-gnueabihf/sys/stat.h:446,
                 from main.c:14:
/usr/include/arm-linux-gnueabihf/bits/statx.h:36:8: note: originally defined here
 struct statx
        ^~~~~
make: *** [makefile:11: main.o] Fehler 1

**Comment by StuartIanNaylor** [comment]
I have stopped playing with Pi to be honest you will just have to support yourself.
Suggest you clone.

**Comment by mstormi** [comment]
Just merge https://github.com/StuartIanNaylor/overlayfs-tools/pull/1

I think that is not specific to RPi but to the debian version (buster)

**Comment by StuartIanNaylor** [comment]
Its not my repo there is the master branch for stretch & the arch branch for buster.
Its both as the libs are different across releases

**Comment by mjeveritt** [comment]
Most likely fixed by #16 FWIW

**Comment by mjeveritt** [comment]
Also in #9

**Comment by UVV-gh** [comment]
If it's not fixed already, it most likely addressed by https://github.com/kmxz/overlayfs-tools/pull/23
